services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_DB: users
      POSTGRES_PASSWORD: postgresP
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, pg_isready, -U, postgres]
      interval: 3s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 3s
      timeout: 3s
      retries: 10

  backend-fastapi:
    build:
      dockerfile: ./backend-fastapi/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8000:80
    volumes:
      - ./backend-fastapi/src:/app/backend-fastapi/src
      - ~/.aws/config:/root/.aws/config:ro
      - ~/.aws/credentials:/root/.aws/credentials:ro
      - ~/.aws/sso:/root/.aws/sso
    env_file:
      - ./docker/.env.aws
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresP
      POSTGRES_DB: users
      POSTGRES_HOST: postgres:5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LOG_LEVEL: INFO
  # REFRESH_DB: true # uncomment to delete all users on startup
  # backend-dotnet:
  #   build:
  #     context: ./backend-dotnet
  #     target: dev
  #   # depends_on:
  #   #   postgres:
  #   #     condition: service_healthy
  #   volumes:
  #     - ./backend-dotnet/api:/src/api
  #     - ./backend-dotnet/api/obj:/src/api/obj:delegated
  #     - ./backend-dotnet/api/bin:/src/api/bin:delegated
  #   ports:
  #     - 5254:8080
  #     - 5000:5000
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgresP
  #     POSTGRES_DB: users
  #     POSTGRES_HOST: postgres:5432
  #     # REFRESH_DB: true # uncomment to delete all users on startup
  frontend:
    depends_on:
      - backend-fastapi
    build:
      context: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true # enable hot reload for devving

volumes:
  postgres_data:
